### ISSUE TITLE
Bug: Compiling from source package does not exist error

### ISSUE THREAD

**Issue by mariakhala** [TomBursch/kitchenowl#227]
### Is this urgent?

Yes

### What parts are affected

Both

### What are the Server/Client versions of KitchenOwl

new

### What's the problem 🤔

E:\kitchenowl-main\kitchenowl\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:19: error: package dev.fluttercommunity.plus.device_info does not exist
      flutterEngine.getPlugins().add(new dev.fluttercommunity.plus.device_info.DeviceInfoPlusPlugin());
                                                                              
i am getting this error

**Comment by TomBursch** [comment]
I guess you're trying to compile it from source? Have you tried running `flutter packages get`?

**Comment by mariakhala** [comment]
Yes I did

**Comment by TomBursch** [comment]
Hmm strange, neither I nor the CI has a problem with building the android app. I've updated all dependencies. Maybe try again with `flutter clean` and then this time `flutter packages upgrade`. What happens if you try to build for a different platform (i.e. windows)? Are you on the latest flutter version?

**Comment by mariakhala** [comment]
I upgraded flutter version as well but not successful I am not using server
i just push the project from GitHub clean and update. This error come
should I install newer version of flutter and try again? Or should I setup
server?
Many thanks

**Comment by mariakhala** [comment]
[image: image.png]

**Comment by TomBursch** [comment]
Thanks for being patient. I can't see the image you've sent, and you don't need to run the backend server to compile the frontend. You'll need the latest version of flutter (3.13.X) to compile the app. What is the output of `flutter doctor`?

**Comment by TomBursch** [comment]
Just FYI, there was an issue with the android build, although with different logs than the ones you posted. It should be fixed now, I also had to bump the minimum java version to 17.

**Comment by mariakhala** [comment]
Excellent, thanks for the heads up! Have you updated it on GitHub?

**Comment by mariakhala** [comment]
i am still getting same error
Running Gradle task 'assembleDebug'...
E:\kitchenowl-main\kitchenowl-main\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:19:
error: package dev.fluttercommunity.plus.device_info does not exist
      flutterEngine.getPlugins().add(new
dev.fluttercommunity.plus.device_info.DeviceInfoPlusPlugin());

  ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
here is flutter doctor
"C:\Users\mmm
developers\Downloads\flutter_windows_3.13.2-stable\flutter\bin\flutter.bat"
doctor --verbose
[!] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version
10.0.19044.3086], locale en-US)
    • Flutter version 3.13.2 on channel stable at C:\Users\mmm
developers\Downloads\flutter_windows_3.13.2-stable\flutter
    ! The flutter binary is not on your path. Consider adding C:\Users\mmm
developers\Downloads\flutter_windows_3.13.2-stable\flutter\bin to your path.
    ! The dart binary is not on your path. Consider adding C:\Users\mmm
developers\Downloads\flutter_windows_3.13.2-stable\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (2 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings;
however it is recommended to use "git" directly to perform update checks
and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version
34.0.0)
    • Android SDK at C:\Users\mmm developers\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build
17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Enterprise 2019
16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual
Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.8.30907.101
    X Visual Studio is missing necessary components. Please re-run the
Visual Studio installer for the "Desktop development with C++" workload,
and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the
latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
17.0.6+0-b2043.56-10027231)

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    •
Android 9 (API 28) (emulator)
    • Windows (desktop)            • windows       • windows-x64    •
Microsoft Windows [Version 10.0.19044.3086]
    • Chrome (web)                 • chrome        • web-javascript •
Google Chrome 116.0.5845.180
    • Edge (web)                   • edge          • web-javascript •
Microsoft Edge 116.0.1938.76

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
Process finished with exit code 0
