### ISSUE TITLE
Bug: Cannot delete a schopping list

### ISSUE THREAD

**Issue by claudiabonitz** [TomBursch/kitchenowl#362]
### Is this urgent?

Yes

### What parts are affected

Frontend

### What is the server version

v93

### What is the client version

04.20

### What platform are you using

Android

### What's the problem 🤔

I created multiple additional shopping lists. One of them was used by interding the shopping items. I could not select the right one an the one which was automatically chosen was wrong. My partner opened that list and afterwards I was no longer able to delete that list.

**Comment by TomBursch** [comment]
This has been fixed with 0.4.21, if you're using fdroid it might take a while for the update to be available.

**Comment by claudiabonitz** [comment]
I switched to version 0.4.21 and yet I'm able to select the right shopping list when inserting items from a recipe. But the problem that I cannot delete a shopping list still persists. In my householt there remain two shopping lists and none of them is deletable. If I add another list I can delete it at least when it is not used by another household member. In my opinion this remains to be a bug.
